/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "finupgroup.com/decision/traincrd/pkg/apis/v1"
	scheme "finupgroup.com/decision/traincrd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	autoscaling "k8s.io/api/autoscaling/v1"
)

// ClusterTraincrdsGetter has a method to return a ClusterTraincrdInterface.
// A group's client should implement this interface.
type ClusterTraincrdsGetter interface {
	ClusterTraincrds() ClusterTraincrdInterface
}

// ClusterTraincrdInterface has methods to work with ClusterTraincrd resources.
type ClusterTraincrdInterface interface {
	Create(*v1.ClusterTraincrd) (*v1.ClusterTraincrd, error)
	Update(*v1.ClusterTraincrd) (*v1.ClusterTraincrd, error)
	UpdateStatus(*v1.ClusterTraincrd) (*v1.ClusterTraincrd, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ClusterTraincrd, error)
	List(opts metav1.ListOptions) (*v1.ClusterTraincrdList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterTraincrd, err error)
	GetScale(clusterTraincrdName string, options metav1.GetOptions) (*autoscaling.Scale, error)
	UpdateScale(clusterTraincrdName string, scale *autoscaling.Scale) (*autoscaling.Scale, error)

	ClusterTraincrdExpansion
}

// clusterTraincrds implements ClusterTraincrdInterface
type clusterTraincrds struct {
	client rest.Interface
}

// newClusterTraincrds returns a ClusterTraincrds
func newClusterTraincrds(c *DecisionV1Client) *clusterTraincrds {
	return &clusterTraincrds{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterTraincrd, and returns the corresponding clusterTraincrd object, and an error if there is any.
func (c *clusterTraincrds) Get(name string, options metav1.GetOptions) (result *v1.ClusterTraincrd, err error) {
	result = &v1.ClusterTraincrd{}
	err = c.client.Get().
		Resource("clustertraincrds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterTraincrds that match those selectors.
func (c *clusterTraincrds) List(opts metav1.ListOptions) (result *v1.ClusterTraincrdList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClusterTraincrdList{}
	err = c.client.Get().
		Resource("clustertraincrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterTraincrds.
func (c *clusterTraincrds) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clustertraincrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterTraincrd and creates it.  Returns the server's representation of the clusterTraincrd, and an error, if there is any.
func (c *clusterTraincrds) Create(clusterTraincrd *v1.ClusterTraincrd) (result *v1.ClusterTraincrd, err error) {
	result = &v1.ClusterTraincrd{}
	err = c.client.Post().
		Resource("clustertraincrds").
		Body(clusterTraincrd).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterTraincrd and updates it. Returns the server's representation of the clusterTraincrd, and an error, if there is any.
func (c *clusterTraincrds) Update(clusterTraincrd *v1.ClusterTraincrd) (result *v1.ClusterTraincrd, err error) {
	result = &v1.ClusterTraincrd{}
	err = c.client.Put().
		Resource("clustertraincrds").
		Name(clusterTraincrd.Name).
		Body(clusterTraincrd).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterTraincrds) UpdateStatus(clusterTraincrd *v1.ClusterTraincrd) (result *v1.ClusterTraincrd, err error) {
	result = &v1.ClusterTraincrd{}
	err = c.client.Put().
		Resource("clustertraincrds").
		Name(clusterTraincrd.Name).
		SubResource("status").
		Body(clusterTraincrd).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterTraincrd and deletes it. Returns an error if one occurs.
func (c *clusterTraincrds) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clustertraincrds").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterTraincrds) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clustertraincrds").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterTraincrd.
func (c *clusterTraincrds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterTraincrd, err error) {
	result = &v1.ClusterTraincrd{}
	err = c.client.Patch(pt).
		Resource("clustertraincrds").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}

// GetScale takes name of the clusterTraincrd, and returns the corresponding autoscaling.Scale object, and an error if there is any.
func (c *clusterTraincrds) GetScale(clusterTraincrdName string, options metav1.GetOptions) (result *autoscaling.Scale, err error) {
	result = &autoscaling.Scale{}
	err = c.client.Get().
		Resource("clustertraincrds").
		Name(clusterTraincrdName).
		SubResource("scale").
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// UpdateScale takes the top resource name and the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *clusterTraincrds) UpdateScale(clusterTraincrdName string, scale *autoscaling.Scale) (result *autoscaling.Scale, err error) {
	result = &autoscaling.Scale{}
	err = c.client.Put().
		Resource("clustertraincrds").
		Name(clusterTraincrdName).
		SubResource("scale").
		Body(scale).
		Do().
		Into(result)
	return
}
