apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hellotypes.foo.com
spec:
  group: foo.com
  version: v1
  scope: Namespaced
  names:
    kind: HelloType
    shortNames: ht
    plural: hellotypes
    singular: hellotype