apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    svc: kodexplorer-app
  name: kodexplorer-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      svc: kodexplorer-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        svc: kodexplorer-app
    spec:
      containers:
        - name: kodexplorer-app
          image: 'decision/kodexplorer:4'
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 100Mi
      terminationGracePeriodSeconds: 30
