apiVersion: v1
kind: Service
metadata:
  labels:
    app: kodexplorer-svc
  name: kodexplorer-svc
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 80
  selector:
    svc: kodexplorer-app
  type: ClusterIP
status:
  loadBalancer: {}
